### ISSUE TITLE
Add --card-format command line switch to override card validation

### ISSUE THREAD

**Issue by uhppoted** [uhppoted/uhppote-cli#12]
Ref. https://github.com/uhppoted/uhppote-core/issues/15

The UHPPOTE controllers seemingly support Wiegand-34 (and possibly other) card formats making the Wiegand-26 validation introduced in v0.8.5 problematic for some systems. However, the validation is useful in avoiding incorrect card numbers due to finger trouble and it would be better to keep it in place.

Proposal is to add a `--card-format <format>` command line switch to the `put-card` and `put-acl` commands override the default validation. The `format` would take the following initial values:

- `wiegand-26`
- ~~`wiegand-34`~~
- `any` (no validation)

**Comment by twystd** [comment]
Seems Wiegand-34 is a "_user defined_" standard:

https://www.idesco.com/files/articles/HID%20-%20Understanding%20card%20formats.pdf

**Comment by twystd** [comment]
Implementation complete - pending release.
