### ISSUE TITLE
get-event <event-id> is requesting event-id + 1

### ISSUE THREAD

**Issue by uhppoted** [uhppoted/uhppote-cli#3]
> ./bin/uhppote-cli --debug get-event 423187757 200
> 
>  ... using default configuration from /usr/local/etc/com.github.uhppoted/uhppoted.conf
>  ... request
>  ...          00000000  17 b0 00 00 2d 55 39 19  c9 00 00 00 00 00 00 00  |....-U9.........|
>  ...          00000010  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
>  ...          00000020  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
>  ...          00000030  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
>  ...          
>  ... sent 64 bytes to 192.168.1.255:60000
>  ... received 64 bytes from 192.168.1.101:60000
>  ... response
>  ...          00000000  17 b0 00 00 2d 55 39 19  c9 00 00 00 02 00 04 01  |....-U9.........|
>  ...          00000010  08 00 00 00 20 20 12 15  13 18 16 17 00 00 00 00  |....  ..........|
>  ...          00000020  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
>  ...          00000030  00 00 00 00 00 00 00 00  8f 29 48 6a 02 03 00 00  |.........)Hj....|
>  ...          
> 423187757  201    2020-12-15 13:18:16 8            4 false 23

**Comment by twystd** [comment]
_next index_ logic was being invoked for both `get-event` _<with index>_ and `get-event <event #>`
