### ISSUE TITLE
Typo in README

### ISSUE THREAD

**Issue by sudobob** [uhppoted/uhppote-cli#6]
In description of store-acl, in example it says 'get-acl'
[https://github.com/uhppoted/uhppote-cli#store-acl ](https://github.com/uhppoted/uhppote-cli#store-acl)

**Comment by twystd** [comment]
Thanks for the heads-up - have pushed a corrected (and slightly updated) README to the _master_ branch.

**Comment by uhppoted** [comment]
Fixed in release v0.6.12
