### ISSUE TITLE
Comunication error

### ISSUE THREAD

**Issue by Uzzi** [uhppoted/uhppote-cli#9]
Hi when I've lunched ./uhppote-cli set-door-delay SERIAL 1 0--->ERROR: Timeout waiting for reply

Can you help me to fix it?
Thank you regards

**Comment by uhppoted** [comment]
Can you run the command in debug mode and attach the output?
```
./uhppote-cli --debug set-door-delay SERIAL 1 0
```

(and also attach your _uhppoted.conf_ file please)

**Comment by uhppoted** [comment]
Ok, there are two things:

1. Unless it's something to do with your network routing tables, the _10.162.34.210:60001_ address looks unusual - the UHPPOTE controllers almost always use port 60000.

2. The command is setting a door delay of 0s - as far as I remember the controllers don't accept a 0 delay. Try:
```
./uhppote-cli --debug set-door-delay SERIAL 1 5
```

**Comment by Uzzi** [comment]
xxxxx and xxxx controllers have a pingable ip from uhppote-cli  vm

**Comment by Uzzi** [comment]
now I've fixed uhppoted.conf:
UT0311-L0x.125042559.Ced = yyyyyyy
UT0311-L0x.125042559.address = 10.162.34.6:60000
UT0311-L0x.125042559.door.1 = Ced

UT0311-L0x.125046859.Ufficio = xxxxxxxx
UT0311-L0x.125046859.address = 10.162.34.5:60000
UT0311-L0x.125042559.door.1 = Lenarduzzi

Now I've to set listener for xxxxx and yyyy:
./uhppote-cli set-listener xxxxxx 10.162.34.5:60000
./uhppote-cli set-listener yyyyy 10.162.34.6:60000

Is it right?

**Comment by uhppoted** [comment]
Getting there :-) .. the controller addresses look correct:

- `UT0311-L0x.125042559.address = 10.162.34.6:60000`
- `UT0311-L0x.125046859.address = 10.162.34.5:60000`

These are the addresses the controllers listen on and almost always use port 60000 so the above looks correct.

The listener address is the address the controllers **send** events to - so it's the IPv4 address of the host machine i.e. the IPv4 address of the VM you're running _uhppote-cli_ on (and the default port is 60001). So if your host machine IP address is 10.162.34.100 you'd want to set it as follows:
```
./uhppote-cli set-listener xxxxxx 10.162.34.100:60001
./uhppote-cli set-listener yyyyy   10.162.34.100:60001
```

**Comment by uhppoted** [comment]
Quick test:
```
./uhppote-cli --debug get-devices
```

That should give you a list of all controllers on your LAN

**Comment by Uzzi** [comment]
Thank you now works fine.
Can you help me about open door notfy by magnetic sensor?

**Comment by uhppoted** [comment]
Umm - I _think_ you mean get door open/close events? if your magnetic sensor is wired to the door inputs on the controller then you need to enabled _record special events_, e.g.
```
./uhppote-cli record-special-events 125042559 true
```
The default controller configuration has door open/close events disabled. You can then see the events using the _listen_ command:
```
./uhppote-cli listen
```

**Comment by Uzzi** [comment]
Thank you so much!

**Comment by Uzzi** [comment]
Now I'have tro study how telgram notify when someone manually open door without rfid id

**Comment by uhppoted** [comment]
Closing this (looks like it's resolved) - feel free to reopen it if necessary.
